server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kafka
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  # Hibernate Configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


